version: '3.9'

services:
  mysql-encurtador:
    image: mysql:8.0
    container_name: mysql-encurtador
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - encurtador-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  encurtador-backend:
    build: ./Backend
    container_name: encurtador-backend
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      mysql-encurtador:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      BASE_URL: ${BASE_URL}
      SCHEDULER_TIME: ${SCHEDULER_TIME}
    networks:
      - encurtador-network

  encurtador-frontend:
    build: 
      context: ./FrontEnd
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: encurtador-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - encurtador-backend
    networks:
      - encurtador-network

volumes:
  mysql-data:

networks:
  encurtador-network:
    driver: bridge
